---

- name: Assorted pre deployment configurations
  hosts: 'all'
  connection: local
  become: True
  tasks:

    - name: Install GPG Key AWS - Step 1
      copy:
        src: amazon-gpg-key
        dest: /etc/pki/rpm-gpg/amazon-gpg-key
    
    - name: install GPG Key AWS - Step 2
      shell:
        cmd: |
          rpm --import /etc/pki/rpm-gpg/amazon-gpg-key

    - name: Ensure Codedeploy Agent dependency is installed
      dnf: 
        name: 'ruby'
        state: installed
        
    - name: Hostname Software dependencies
      dnf: 
        name: uuid
        state: installed

    - name: Update the system
      dnf: 
       name: '*'
       state: latest