---

# Apply DISA STIG
- ansible.builtin.import_playbook: './stig_rhel.yml'

# Apply custom STIG Addons
- ansible.builtin.import_playbook: './stig_rhel_addons.yml'

# Software Prerequisites
- ansible.builtin.import_playbook: './misc_install_settings.yml'

# Setup and install Cloudwatch agent
- ansible.builtin.import_playbook: './deploy_cloudwatch_agent.yml'

# Stage software to be install on image first run
- ansible.builtin.import_playbook: './software_staging.yml'