---

- name: Stage Software For Install at First Bootup
  hosts: 'all'
  become: True
  connection: local
  tasks:
    - name: Install EPEL Repo
      dnf: 
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
        state: installed
        
    - name: Ensure that software deps are installed
      dnf: 
        name: 
         - httpd
         - mod_ssl
         - firewalld
        state: installed

    - name: Copy the specified file from our S3 bucket and ensure that it is good
      copy:
        content: |
          #!/bin/bash
          /usr/bin/aws s3 help
          /usr/bin/aws s3 ls
          /usr/bin/aws s3 cp {{ software_s3_bucket }} /root/
          cd /root/
          sha256sum /root/*.tar | grep {{ software_tar_hash }}
          tar -xf ./*.tar
          /bin/bash ./staging.sh
        dest: "/staging/software_staging.sh"
        mode: 777
        owner: root

    - name: Enable httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true
