all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      become: true
      cdk_stack_base_name: TekPossible-Stratagem
      scc_download_url: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.10_rhel9_x86_64_bundle.zip
      software_s3_bucket: s3://tekpossible-stratagem-s3-bucket/tekpossible-ha-52d57c35de6f.tar
      software_tar_hash: 1b8f21710b2b2a42db40adc338ed854107ada1f6ecc1047cf5c4ccc8b03f87fa
      wazuh_manager_hostname: wazuh.tekpossible.com
