all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      become: true
      cdk_stack_base_name: TekPossible-Stratagem
      software_s3_bucket: s3://tekpossible-stratagem-s3-bucket/tekpossible-ha-0eea2e13c980.tar
      software_tar_hash: c88aae0c2b8398a2191708b91f585486777a00414b81dd58a19baa5d292d219b
      wazuh_manager_hostname: wazuh.tekpossible.com
