all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      become: true
      cdk_stack_base_name: TekPossible-Stratagem
      scc_download_url: "https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.10.1_rhel9_oracle-linux9_x86_64_bundle.zip"
      software_s3_bucket: s3://tekpossible-stratagem-s3-bucket/tekpossible-ha-52d57c35de6f.tar
      software_tar_hash: 1b8f21710b2b2a42db40adc338ed854107ada1f6ecc1047cf5c4ccc8b03f87fa
      cloudwatch_log_rention_days: 60
      cloudwatch_tracked_logs:
        - {log_path: "/var/log/messages", log_name: "var-log-messages"}
        - {log_path: "/var/log/secure", log_name: "var-log-secure"}
        - {log_path: "/var/log/audit/audit.log", log_name: "var-log-audit"}
        - {log_path: "/var/log/httpd/error_log", log_name: "httpd-error-log"}
        - {log_path: "/var/log/httpd/access_log", log_name: "httpd-access-log"}
        - {log_path: "/var/log/httpd/ssl_error_log", log_name: "httpd-ssl-error-log"}
        - {log_path: "/var/log/httpd/ssl_access_log", log_name: "httpd-ssl-access-log"}
