all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      become: true
      cdk_stack_base_name: TekPossible-Stratagem
      software_s3_bucket: s3://tekpossible-stratagem-s3-bucket/tekpossible-ha-b5cfdafc87f7.tar
      software_tar_hash: de2b3714f898a28dbe5feafc17d04d2a546eb560b88b4c6d8624f2b3e60dd8b4
      wazuh_manager_hostname: wazuh.tekpossible.com
