all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      become: true
      cdk_stack_base_name: TekPossible-Stratagem
      software_s3_bucket: s3://tekpossible-stratagem-s3-bucket/tekpossible-ha-52d57c35de6f.tar
      software_tar_hash: 720ad81c6ecde2bb0ecd3e94a26b68ac9ae0b36c65c9bb532f81f9de588abadb
      wazuh_manager_hostname: wazuh.tekpossible.com
      scc_download_url: "https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.10_rhel9_x86_64_bundle.zip"
