all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      become: true
      cdk_stack_base_name: TekPossible-Stratagem
      software_s3_bucket: s3://tekpossible-stratagem-s3-bucket/tekpossible-ha-0eea2e13c980.tar
      software_tar_hash: f15e3284077cca4fe151921beb11448d6dbe0aa4efe8f8d1f784df4727379d64
      wazuh_manager_hostname: wazuh.tekpossible.com
