localhost:
  ansible_host: 127.0.0.1
  become: true
  cdk_stack_base_name: TekPossible-Stratagem
  software_s3_bucket: s3://tekpossible-stratagem-s3-bucket/tekpossible-ha-0eea2e13c980.tar
  software_tar_hash: 32da93ed3cb57199c08b9b8c74196151953d7db3f9754bdae8cd248e72d7e031
  wazuh_manager_hostname: wazuh.tekpossible.com
