---

localhost:
  ansible_host: '127.0.0.1'
  become: True
  wazuh_manager_hostname: 'wazuh.tekpossible.com' # No longer exists, but I can bring it back for the cloud hosts
  software_s3_bucket: "BUCKET_URL_HERE" # The S3 Bucket will go here when the CI/CD pipeline for software completes
  software_tar_hash: "SOFTWARE_TAR_HASH_HERE" # The hash of the software tar bundle will go here when the CI/CD pipeline for software completes